name: Deploy Theme to Dev Server via FTP

on:
  push:
    branches:
      - dev

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
    # Шаг 1: Клонирование репозитория
    - name: Checkout repository
      uses: actions/checkout@v3

    # Шаг 2: Архивация папки с темой
    - name: Archive theme
      run: |
        cd wp-content/themes
        zip -r theme.zip your-theme-folder-name

    # Шаг 3: Загрузка архива на сервер через FTP
    - name: Upload theme archive via FTP
      uses: SamKirkland/FTP-Deploy-Action@4.3.0
      with:
        server: clio.cityhost.com.ua
        username: chf6b5697a_jfit
        password: npBlxJoruf
        protocol: ftp
        port: 21
        local-dir: wp-content/themes/
        server-dir: /var/www/chf6b5697a/www/jfit.beautiful-website.space/wp-content/themes/

    # Шаг 4: Удаление старой версии темы и разархивирование новой
    - name: Update theme
      run: |
        cd /var/www/chf6b5697a/www/jfit.beautiful-website.space/wp-content/themes/
        rm -rf your-theme-folder-name
        unzip theme.zip -d .
        rm -f theme.zip